- hosts: all
  become: yes
  tasks:
    - name: installing httpd
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
    - name: installing apache2
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
